{{- if .Values.configMaps }}
{{- range .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  labels:
    {{- include "typicalapp.labels" $ | nindent 4 }}
data:
  {{- toYaml .data | nindent 2 }}
{{- end }}
{{- end }}
# {{- if .Values.envConfigMaps }}
# ---
# {{- range .Values.envConfigMaps }}
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: {{ .name }}
#   labels:
#     {{- include "typicalapp.labels" $ | nindent 4 }}
# data:
#   {{- toYaml .data | nindent 2 }}
# {{- end }}
# {{- end }}
 # {{- range $key, $value := .data }}
 # {{ $key }}: {{ toYaml $value | nindent 2 }}
 # {{- end }}